max_steps: 6
num_sentences: 50
task: "qa2_two-supporting-facts"
noise_train_path: "data/pg19-with-sentences/train"
noise_test_path: "data/pg19-with-sentences/test"
facts_train_path: data/tasks_1-20_v1-2/en-10k/${envs.task}_train.txt
facts_test_path: data/tasks_1-20_v1-2/en-10k/${envs.task}_test.txt
# noise_train_path: "/home/nazar/projects/data_sources/babilong/pg19-with-sentences/train"
# noise_test_path: "/home/nazar/pg19-test-with-sentences"
# facts_train_path: /home/nazar/tasks_1-20_v1-2/en-10k/${envs.task}_train.txt
# facts_test_path: /home/nazar/tasks_1-20_v1-2/en-10k/${envs.task}_test.txt


# Core Environment Configuration
env:
  _target_: rl.babilong_env.BabilongEnv
  max_steps: ${envs.max_steps}
  reward_model:
    _target_: rl.babilong_env.PositionalGTReward
  # Dataset Configuration
  dataset:
    _target_: envs.babilong.retrieval_babilong.RetrievalBabiLong
    num_sentences: ${envs.num_sentences}
    
    task_dataset:
      _target_: envs.babilong.babilong_fix.QA2FixWrapper
      dataset:
        _target_: envs.babilong.babilong_utils.TaskDataset
        dataset_path: ${envs.facts_train_path}
      add_sentence_idx: false
    
    noise_sentence_sampler:
      _target_: envs.babilong.retrieval_babilong.RetrSentenceSampler
      dataset:
        _target_: datasets.load_from_disk
        dataset_path: ${envs.noise_train_path}


test_env:
  _target_: rl.babilong_env.BabilongEnv
  max_steps: ${envs.env.max_steps}
  reward_model:
    _target_: rl.babilong_env.PositionalGTReward
  dataset:
    _target_: envs.babilong.retrieval_babilong.RetrievalBabiLong
    num_sentences: ${envs.env.dataset.num_sentences}
    
    task_dataset:
      _target_: envs.babilong.babilong_fix.QA2FixWrapper
      dataset:
        _target_: envs.babilong.babilong_utils.TaskDataset
        dataset_path: ${envs.facts_test_path}
      add_sentence_idx: false
    
    noise_sentence_sampler:
      _target_: envs.babilong.retrieval_babilong.RetrSentenceSampler
      dataset:
        _target_: datasets.load_from_disk
        dataset_path: ${envs.noise_test_path}


