defaults:
  - envs: babilong 
  - algo: pqn
  - logger: tb
  - _self_

seed: 42
device: 'cuda:1'
learning_start: 200
steps_count: 50_000
batch_size: 32
eval_interval: 20
eval_episodes: 100
envs_parallel: 2
max_state_length: 512
max_action_length: 64
